import React, { useEffect } from 'react';
import { Download, FileJson, FileText } from 'lucide-react';
import { api } from '../../../api/client';
import { useInvestigation } from '../../../context/InvestigationContext';
import { ForensicHash } from '../../common/ForensicHash';
import { Panel } from '../../common/Panel';
import { EmptyState, ErrorState, SkeletonRows } from '../../common/StateViews';
import { ReportDocumentView } from './ReportDocumentView';

const FORMATS = [
  { fmt: 'html' as const, label: 'HTML', icon: FileText, primary: true },
  { fmt: 'pdf' as const, label: 'PDF', icon: Download, primary: false },
  { fmt: 'json' as const, label: 'JSON', icon: FileJson, primary: false },
];

export const ReportExperience: React.FC = () => {
  const { activeRunId, activeRun, reports, reportDoc, reportStatus, reportError, loadReport, isUsingFixtures } = useInvestigation();

  useEffect(() => {
    if (reportStatus === 'idle' && !isUsingFixtures) loadReport();
  }, [reportStatus, isUsingFixtures, loadReport]);

  if (!activeRunId) {
    return <div className="sms-page"><Panel><EmptyState title="Run an analysis to generate a report" /></Panel></div>;
  }

  let preview: React.ReactNode;
  if (isUsingFixtures) preview = <EmptyState title="Reports are generated by the analysis engine" detail="The engine is unavailable, so no report exists for this demo data." />;
  else if (reportStatus === 'error') preview = <ErrorState title="Report generation failed" detail={reportError} onRetry={loadReport} />;
  else if (reportStatus !== 'ready' || !reportDoc) preview = (
    <div className="sms-stack" style={{ padding: 'var(--ds-space-24)' }}>
      <p className="sms-muted" role="status" style={{ fontSize: 'var(--ds-text-13)' }}>Generating report…</p>
      <SkeletonRows rows={8} height={20} gap="var(--ds-space-12)" />
    </div>
  );
  else preview = <ReportDocumentView doc={reportDoc} run={activeRun} />;

  return (
    <div className="sms-page">
      <header className="sms-page-head">
        <div>
          <h1 className="sms-page-title">Report</h1>
          <p className="sms-page-sub">The engine renders the report from the stored assessment. Downloads are the engine's own HTML, PDF and JSON files; the preview below is drawn from the JSON rendition.</p>
        </div>
        <div style={{ display: 'flex', gap: 'var(--ds-space-8)' }}>
          {FORMATS.map(({ fmt, label, icon: Icon, primary }) => (
            <a
              key={fmt}
              className={`sms-btn${primary ? ' sms-btn--primary' : ''}`}
              href={api.getReportUrl(activeRunId, fmt, true)}
              download
              aria-disabled={isUsingFixtures}
              style={isUsingFixtures ? { pointerEvents: 'none', opacity: 0.5 } : undefined}
            >
              <Icon size={14} aria-hidden="true" />
              Download {label}
            </a>
          ))}
        </div>
      </header>

      {reports.length > 0 && (
        <Panel title="Report artifacts" flush>
          <table className="sms-table">
            <thead>
              <tr><th>Format</th><th>Renderer</th><th>Schema</th><th>Status</th><th>SHA-256</th></tr>
            </thead>
            <tbody>
              {reports.map((r) => (
                <tr key={r.format}>
                  <td className="sms-mono sms-cell-title">{r.format.toUpperCase()}</td>
                  <td className="sms-mono">{r.renderer_version ?? '—'}</td>
                  <td className="sms-mono">{r.report_schema_version ?? '—'}</td>
                  <td>{r.generated ? 'rendered' : 'renders on first download'}</td>
                  <td>{r.report_sha256 ? <ForensicHash value={r.report_sha256} length={16} /> : <span className="sms-muted">—</span>}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Panel>
      )}

      <Panel title="Preview" flush>{preview}</Panel>
    </div>
  );
};
